[project]
name = "p3dh"
version = "0.2.0"
description = "EBA Pillar 3 Data Hub â€“ universal P3DH fact database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
]
